"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    secretKey: process.env.SECRET_KEY || 'tn-connect-secret-2026',
    host: process.env.HOST || 'http://0.0.0.0',
    port: process.env.PORT || '21465',
    deviceName: process.env.DEVICE_NAME || 'TN Connect',
    poweredBy: 'WPPConnect-Server',
    startAllSession: true,
    tokenStoreType: process.env.TOKEN_STORE || 'file',
    maxListeners: 15,
    customUserDataDir: './userDataDir/',
    webhook: {
        url: process.env.WEBHOOK_URL || null,
        autoDownload: true,
        uploadS3: false,
        readMessage: true,
        allUnreadOnStart: false,
        listenAcks: true,
        onPresenceChanged: true,
        onParticipantsChanged: true,
        onReactionMessage: true,
        onPollResponse: true,
        onRevokedMessage: true,
        onLabelUpdated: true,
        onSelfMessage: false,
        ignore: ['status@broadcast'],
    },
    websocket: {
        autoDownload: false,
        uploadS3: false,
    },
    chatwoot: {
        sendQrCode: true,
        sendStatus: true,
    },
    archive: {
        enable: false,
        waitTime: 10,
        daysToArchive: 45,
    },
    log: {
        level: process.env.LOG_LEVEL || 'info',
        logger: ['console', 'file'],
    },
    createOptions: {
        browserArgs: [
            '--disable-web-security',
            '--no-sandbox',
            '--disable-web-security',
            '--aggressive-cache-discard',
            '--disable-cache',
            '--disable-application-cache',
            '--disable-offline-load-stale-cache',
            '--disk-cache-size=0',
            '--disable-background-networking',
            '--disable-default-apps',
            '--disable-extensions',
            '--disable-sync',
            '--disable-dev-shm-usage',
            '--disable-gpu',
            '--disable-translate',
            '--hide-scrollbars',
            '--metrics-recording-only',
            '--mute-audio',
            '--no-first-run',
            '--safebrowsing-disable-auto-update',
            '--ignore-certificate-errors',
            '--ignore-ssl-errors',
            '--ignore-certificate-errors-spki-list',
        ],
        linkPreviewApiServers: null,
    },
    mapper: {
        enable: false,
        prefix: 'tagone-',
    },
    db: {
        mongodbDatabase: 'tokens',
        mongodbCollection: '',
        mongodbUser: '',
        mongodbPassword: '',
        mongodbHost: '',
        mongoIsRemote: true,
        mongoURLRemote: process.env.MONGO_URL || '',
        mongodbPort: 27017,
        redisHost: 'localhost',
        redisPort: 6379,
        redisPassword: '',
        redisDb: 0,
        redisPrefix: 'docker',
    },
    aws_s3: {
        region: 'sa-east-1',
        access_key_id: null,
        secret_key: null,
        defaultBucketName: null,
        endpoint: null,
        forcePathStyle: null,
    },
};
